{% set name = "acpype" %}
{% set version = "2022.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/alanwilter/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a3d2551ae2d6264b87c7f5432ba3977e6f27ccc8049010a4f7c3359fbfd67fdb
build:
  number: 0
  script:
    - mv recipe/setup_conda.py setup.py
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - acpype=acpype.cli:init_main
requirements:
  host:
    - python >=3
    - poetry
    - pip
  run:
    - openbabel
    - python >=3
    - ambertools
    - parmed
    - numpy
    - scipy
    - matplotlib-base

test:
  commands:
    - acpype -h
about:
  home: https://github.com/alanwilter/acpype
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Generates topologies for chemical compounds
  description: |
    A tool based in Python to use Antechamber to generate topologies 
    for chemical compounds and to interface with other python 
    applications like CCPN or ARIA.

  doc_url: https://github.com/alanwilter/acpype
  dev_url: https://github.com/alanwilter/acpype

extra:
  recipe-maintainers:
    - alanwilter
    - lkagami
    - simonbray
