{% set name = "acpype" %}
{% set version = "2021.11.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/alanwilter/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 246fd32af1f40769acd37f6294ebd25ddc8c0838dda19fc6c41448e1d184e951
build:
  number: 0
  script:
    - mv recipe/setup_conda.py setup.py
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - acpype=acpype_lib.acpype:init_main
requirements:
  host:
    - python >=3
    - pip
  run:
    - openbabel
    - python >=3
    - ambertools
    - parmed
    - numpy
    - scipy
    - matplotlib-base

test:
  commands:
    - acpype -h
about:
  home: https://github.com/alanwilter/acpype
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Generates topologies for chemical compounds
  description: |
    A tool based in Python to use Antechamber to generate topologies 
    for chemical compounds and to interface with other python 
    applications like CCPN or ARIA.

  doc_url: https://github.com/alanwilter/acpype
  dev_url: https://github.com/alanwilter/acpype

extra:
  recipe-maintainers:
    - alanwilter
    - lkagami
    - simonbray
