travis:
  secure:
    BINSTAR_TOKEN: DqTLxfyEVVy1mVQeQUvFRCW7V/BU7t3XKktq+YqqwqMwzogCsDcMDJoNTp4N2kPpR6chfkLaiy63Tlur05esuIUD6cz50WyVTguqyEgCNth6BeNAxJAlf6w+I+CazQd/pCSRzN8hM4Le4FHDlFFTU+W1CJEOgYuUj6QmimbbHJOC22k8k83LHZNKPsw1PoXUrrghd+sr2mPCgS7wqPHm+slhfBJ8JfgwQ9hwhlHytFFi8AJtjjZqFRrw5Af46ZcuHPMOiSvsKKTrBXtTC8iS7KfNUMuXtFJRnWvsTBPlz55HKNJT5aRv2bfc9v2BwIezUg73V4/7ftlTbtzo5PnMZQlScFaaEySmuUaxj/kl90kwDexnnUoxEA78EjbAfCJphzcK91eScAEbtzFogkY2a5SHip5B94O0owmSuBcCswtLQOGcK222UdVO4NTcJxeBPw7lNQHq3+daioETBvmQBw4Wkpqhv+S6wkoxHPllqsm4CpawQ4DQKeB19TGWauY+pqFVyH8egipfXJlgyzwczTTa1eslHOsD3T09QrI1LLhW2pAijqt76cOiB09w++Hpifsberus1SssTnzFmkGEiIHKjET+Dn7qjRwqaj+M6p56ZR16mdPAtHIlx0tVaqAA2U39G0ltNEj5+S48Z+aY7qkQWulWrVM7h0IF1kgJe8I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
